routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\PresensiController;
use App\Http\Controllers\GolonganController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/tes', function () {
    return view('admin.print_all_presence');
});

Route::get('tes2', [PresensiController::class,'allEmployee']);
Route::get('tes3', [PresensiController::class,'allEmployeeFilter'])->name('presence.filter');

Auth::routes();

Route::get('/reload-captcha', [LoginController::class, 'reloadCaptcha']);
//Admin Home page after login
Route::group(['middleware'=>'admin'], function() {
    Route::get('/admin/home', [HomeController::class,'index'])->name('admin.home');
    Route::post('/admin/cari-pegawai', [HomeController::class,'searchEmployee'])->name('dashboard.search');
    Route::resource('pegawai', PegawaiController::class);
    Route::post('/pegawai/cari', [PegawaiController::class,'search'])->name('search.employee');
    Route::resource('jabatan', JabatanController::class);
    Route::resource('golongan', GolonganController::class);
    Route::get('/admin/pegawai/presensi/{id}', [HomeController::class,'employeePresence'])->name('presensi.pegawai');
    Route::get('/admin/pegawai/presensi-cetak', [HomeController::class,'printPresence'])->name('cetak.presensi');
    Route::get('/admin/presensi-pegawai', [PresensiController::class,'allEmployee'])->name('presensi.keseluruhan');
    Route::get('/admin/presensi-pegawai/filter', [PresensiController::class,'allEmployeeFilter'])->name('presence.all.filter');
    Route::get('/admin/presensi-pegawai/print', [PresensiController::class,'allEmployeePrint'])->name('presence.all.print');
    Route::get('/admin/presensi-pegawai/izin/{id}', [PresensiController::class,'employeePermit'])->name('presence.record.permit');
    Route::get('/admin/presensi-pegawai/sakit/{id}', [PresensiController::class,'employeeSick'])->name('presence.record.sick');
    Route::get('/admin/presensi-pegawai/alpa/{id}', [PresensiController::class,'employeeAlpa'])->name('presence.record.alpa');
});

Route::group(['middleware'=>'auth'], function() {
    Route::get('/', [HomeController::class,'index'])->name('home');
    Route::get('/profil', [HomeController::class,'profile'])->name('profile');
    Route::resource('presensi', PresensiController::class);
    Route::get('/catat-kehadiran', [PresensiController::class,'store'])->name('catat.kehadiran');
    Route::get('/catat-izin', [PresensiController::class,'permit'])->name('permit');
});

resources/views/admin/employee/index.blade.php
@extends('base')
@section('plugin')
    <!-- bs-custom-file-input -->
    <script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
@endsection
@section('content')
<!-- Content Header (Page header) -->
<x-page-header name="Pegawai" :section="$page ?? ''"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div id="accordion">
            <div class="card card-primary">
                <div class="card-header">
                    <h4 class="card-title w-100">
                    <a class="d-block w-100" data-toggle="collapse" href="#collapseOne">
                        <span><i class="nav-icon fas fa-search"></i></span>&nbsp;&nbsp;Pencarian
                    </a>
                    </h4>
                </div>
                <div id="collapseOne" class="collapse @isset($request) show @endisset" data-parent="#accordion">
                    <form action="{{route('search.employee')}}" method="POST">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="value">NIP/Nama Karyawan</label>
                                <input type="text" class="form-control" id="value" name="value" placeholder="masukan NISN/Nama pegawai" value="{{old('nisn',$request->value ?? "")}}" required>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary">Cari</button>
                            @isset($request)
                            <a href="{{route('pegawai.index')}}" class="btn btn-danger">Batalkan</a>
                            @endisset
                        </div>
                      </form>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card">
                    <div class="card-header">
                        <div style="float:left" class="card-title">List Data</div>
                        <div style="float:right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                {{-- <button type="button" class="btn btn-default btn-sm" data-toggle="modal"
                                    data-target="#modal-sm">
                                    Import Data pegawai
                                </button> --}}
                                <a href="{{route('pegawai.create')}}" class="btn btn-primary btn-sm">Tambah Data</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Nama</th>
                                    <th>NIP</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $x=1?>
                                @foreach ($employees as $key => $employee)
                                <tr>
                                    <td>{{$employees->firstItem() + $key}}</td>
                                    <td>{{$employee->nama}}</td>
                                    <td>{{$employee->nip}}</td>
                                    <td>{{$employee->status_pegawai}}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-info" href="{{route('pegawai.show',$employee->id)}}"><i
                                                    class="fa fa-eye"></i></a>
                                            <a class="btn btn-warning" href="{{route('pegawai.edit',$employee->id)}}"><i
                                                    class="fa fa-pen"></i></a>
                                            @if (auth()->user()->id != $employee->id)
                                            <form action="{{route('pegawai.destroy',$employee->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger delete-data" type="submit"><i
                                                        class="fa fa-trash"></i></button>
                                            </form>
                                            @endif
                                            <a class="btn btn-success" href="{{route('presensi.pegawai',$employee->id)}}"><i
                                                class="fa fa-list"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {{$employees->setPath(url()->current())->links('pagination::bootstrap-4')}}
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
        {{-- <div class="modal fade" id="modal-sm">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Import Data pegawai</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('employee.import')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <p>Pastikan mengikuti format excel yang telah disediakan sebelum melakukan import data</p>
                            <p><a href="{{route('employee.format.export')}}" class="btn btn-success btn-sm">Download
                                    Format Excel</a></p>

                            <div class="form-group">
                                <label for="employeeImport">Upload File Excel</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="employeeImport"
                                            name="employeeImport" required>
                                        <label class="custom-file-label" for="employeeImport">Pilih file</label>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="page" value="{{$page}}">

                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Proses</button>
                        </div>
                </div>
                </form>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div> --}}

        <!-- /.modal -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

@section('javascript')
<!-- bs-custom-file-input -->
<script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        bsCustomFileInput.init();

    });
  </script>
@endsection

resources/views/admin/employee/show.blade.php
@extends('base')
@section('content')
<!-- Content Header (Page header) -->
<x-page-header name="Pegawai" :section="$page ?? ''" />
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle"
                                        src="{{asset('storage/foto/'.$employee->foto)}}" alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{$employee->nama}}</h3>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header p-2">
                        <ul class="nav nav-pills">
                            <li class="nav-item"><a class="nav-link active" href="#settings"
                                    data-toggle="tab">Biodata</a></li>
                        </ul>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <div class="tab-content">

                            <div class="active tab-pane" id="settings">
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <td>NIP</td>
                                            <td>{{$employee->nip}}</td>
                                        </tr>
                                        <tr>
                                            <td>Nama</td>
                                            <td>{{$employee->nama}}</td>
                                        </tr>
                                        <tr>
                                            <td>Alamat</td>
                                            <td>{{$employee->alamat}}</td>
                                        </tr>
                                        <tr>
                                            <td>Tempat Lahir</td>
                                            <td>{{$employee->tempat_lahir}}</td>
                                        </tr>
                                        <tr>
                                            <td>Tanggal Lahir</td>
                                            <td>{{date('d-m-Y', strtotime($employee->tanggal_lahir))}}</td>
                                        </tr>
                                        <tr>
                                            <td>Agama</td>
                                            <td>{{$employee->agama}}</td>
                                        </tr>
                                        <tr>
                                            <td>Pendidikan</td>
                                            <td>{{$employee->pendidikan}}</td>
                                        </tr>
                                        <tr>
                                            <td>Jurusan</td>
                                            <td>{{$employee->jurusan}}</td>
                                        </tr>
                                        <tr>
                                            <td>Jenis Kelamin</td>
                                            <td>{{$employee->jenis_kelamin}}</td>
                                        </tr>
                                        <tr>
                                            <td>Status Menikah</td>
                                            <td>{{$employee->status_pernikahan}}</td>
                                        </tr>
                                        <tr>
                                            <td>Jabatan</td>
                                            <td>{{$employee->jabatan->nama}}</td>
                                        </tr>
                                        <tr>
                                            <td>Status Kepegawaian</td>
                                            <td>{{$employee->status_pegawai}}</td>
                                        </tr>
                                        @if ($employee->status_pegawai == "pns")
                                        <tr>
                                            <td>Golongan PNS</td>
                                            <td>{{$employee->golongan->nama}}</td>
                                        </tr>
                                        @endif
                                        <tr>
                                            <td>Tahun Diterima</td>
                                            <td>{{$employee->tahun_masuk}}</td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{{route('pegawai.index')}}" class="btn btn-danger">Kembali</a>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection